SELECT
    c.NATIONALITY AS country,
    COUNT(*)      AS review_count
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED f
JOIN SKYTRAX_REVIEWS_DB.MARTS.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.NATIONALITY IS NOT NULL
  AND c.NATIONALITY <> ''
GROUP BY c.NATIONALITY
ORDER BY review_count DESC
LIMIT 10;